-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    available_balance DECIMAL(12,2),
    portfolio_value DECIMAL(12,2) NOT NULL DEFAULT 0
);

-- CREATE TABLE Products (
--     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name VARCHAR(255) UNIQUE NOT NULL,
--     price DECIMAL(12,2) NOT NULL,
--     available BOOLEAN DEFAULT TRUE
-- );

CREATE TABLE Stocks(
    ticker VARCHAR(20) NOT NULL,
    name VARCHAR(300),
    sector VARCHAR(300),
    PRIMARY KEY (ticker)
);

CREATE TABLE TimeData (
    ticker VARCHAR(20) NOT NULL REFERENCES Stocks(ticker),
    period DATE NOT NULL,
    closePrice DECIMAL(12,2),
    highPrice DECIMAL(12,2),
    lowPrice DECIMAL(12,2),
    transactionCount INT,
    openPrice DECIMAL(12,2),
    tradingVolume DECIMAL(12,2),
    volumeWeightedAveragePrice DECIMAL(12,2),
    PRIMARY KEY (ticker,period)

);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    ticker VARCHAR(20) NOT NULL REFERENCES Stock(ticker),
    quantity DECIMAL(12,2) NOT NULL,
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'EST')
);

CREATE TABLE Accounts(
  id INT NOT NULL REFERENCES Users(id),
  ticker VARCHAR(20) NOT NULL REFERENCES Stocks(ticker),
  shares_quantity DECIMAL(12,2) NOT NULL,
  monetary_value DECIMAL(12,2) NOT NULL
);

CREATE TABLE Articles(
  aid INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  uid INT NOT NULL REFERENCES Users(id),
  ticker VARCHAR(20) NOT NULL REFERENCES Stocks(ticker),
  rating INT,
  article_text VARCHAR(500) NOT NULL 
)
