CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    available_balance DECIMAL(12,2),
    portfolio_value DECIMAL(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    ticker VARCHAR(20) NOT NULL REFERENCES Stocks(ticker),
    quantity DECIMAL(12,2) NOT NULL,
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'EST')
);

CREATE TABLE Accounts(
  id INT NOT NULL REFERENCES Users(id),
  ticker VARCHAR(20) NOT NULL REFERENCES Stocks(ticker),
  shares_quantity DECIMAL(12,2) NOT NULL,
  monetary_value DECIMAL(12,2) NOT NULL
);

CREATE TABLE Articles(
  aid INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  uid INT NOT NULL REFERENCES Users(id),
  ticker VARCHAR(20) NOT NULL REFERENCES Stocks(ticker),
  rating INT,
  article_text VARCHAR(500) NOT NULL 
)